FROM docker.io/nginx:stable-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY indico.conf /etc/nginx/conf.d/
COPY \
    --from=uwsgi \
    /opt/indico/.venv/lib/python3.11/site-packages/indico/web/static/ \
    /opt/indico/web/static/
RUN rm /etc/nginx/conf.d/default.conf
